language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run semantic-release

env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy --auth $NETLIFY_ACCESS_TOKEN -p --dir=./build
  skip_cleanup: true
  on:
    branch: layout
