language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run ci:test
  - npm run semantic-release

env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g

deploy:
  provider: script
  script: npm run ci:deploy
  skip_cleanup: true
  on:
    branch: interactive
